name: 'Packaging extension'

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
          run_install: true

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 20.x
          cache: 'pnpm'
      - name: Build and package extension for all browsers
        run: pnpm compose:all
        env:
          CRX_ID: ${{ vars.CRX_ID }}
          CRX_KEY: ${{ secrets.CRX_KEY }}
          PLASMO_PUBLIC_CRX_ID: ${{ vars.PLASMO_PUBLIC_CRX_ID }}
          PLASMO_PUBLIC_API_BASE_URL: ${{ vars.PLASMO_PUBLIC_API_BASE_URL }}
          PLASMO_PUBLIC_APP_URL: ${{ vars.PLASMO_PUBLIC_APP_URL }}

      - name: Change owner of build directory
        run: |
          sudo chown -R runner:docker build/

      - name: Create Release
        run: |
          gh release create ${{ github.ref }} \
          --generate-notes \
          build/brave-mv3-prod.zip \
          build/chrome-mv3-prod.zip \
          build/edge-mv3-prod.zip \
          build/firefox-mv2-prod.zip \
          build/firefox-mv3-prod.zip \
          build/opera-mv3-prod.zip \
          build/safari-mv3-prod.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GRAINED_GITHUB_TOKEN }}
